build:
  image: phpunit/phpunit
  commands:
    - apt-get update
    - apt-get -y install sudo
    - cd /
    - git clone https://github.com/sass/libsass.git
    - export SASS_LIBSASS_PATH=/libsass/
    - git clone https://github.com/sass/sassc.git
    - cd ./sassc
    - make
    - sudo ln ./bin/sassc /usr/bin/sassc
    - phpunit test/travis/test.php